### ISSUE TITLE
可以更新下模型选项吗？

### ISSUE THREAD

**Issue by kurtn2005** [streetlight3316/toolbox#2]
我尝试修改了下node_modules/chatgpt/build/index.js 和index.js.map里的text-davinci-003，换成了gpt-3.5-turbo。但是失败了。
我想把模型换成chatgpt的api的模型gpt-3.5-turbo，不知道怎么换。

**Comment by kurtn2005** [comment]
哦，我刚刚看了官方文档。OpenAI换了新的endpoint给ChatGPT的API。应该不是简单换个模型名字就能用的。

**Comment by streetlight3316** [comment]
> 哦，我刚刚看了官方文档。OpenAI换了新的endpoint给ChatGPT的API。应该不是简单换个模型名字就能用的。

是的，后续直接用openai的官方依赖调用了，我等下更新上来

![image](https://user-images.githubusercontent.com/66906265/222407152-b8ad5a64-a07c-432e-8d65-5e6a35d67e89.png)
