### ISSUE TITLE
关于保护API key安全

### ISSUE THREAD

**Issue by zhaolu1206** [streetlight3316/toolbox#7]
现在的情况是如果发生错误，在返回的错误信息中会有API key的信息，能否改变设定让它不要返回这个信息？

**Comment by zhaolu1206** [comment]
![Uploading Screenshot_20230307-095157.png…]()

**Comment by streetlight3316** [comment]
可以的,修改`service/openai.js`
代码第55行可以控制异常输出

**Comment by zhaolu1206** [comment]
> 可以的,修改`service/openai.js` 代码第55行可以控制异常输出

OK，谢谢

**Comment by zhaolu1206** [comment]
> > 可以的,修改`service/openai.js` 代码第55行可以控制异常输出
> 
> OK，谢谢

**Comment by zhaolu1206** [comment]
![image](https://user-images.githubusercontent.com/30510452/223423436-4845effc-5d35-45c4-b934-fe6c331cb220.png)
你好，我不清楚应该改哪里

**Comment by streetlight3316** [comment]
前面我理解错您的意思了，想要控制返回异常信息中不包含ApiKey的话可以修改61行 `content:JSON.stringify(error)`
`error`中包含了所有异常信息,您可以对返回的error做过滤处理，去除不需要的内容，或者自定义返回信息，过滤后按照原来格式`content:过滤后的error`返回即可
